apiVersion: v1
kind: PersistentVolume
metadata:
  name: osportalapi-pv-volume
  labels:
    type: local
spec:
  storageClassName: osportalapi-pv-volume
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osportalapi-pv-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: osportalapi-claim0
  name: osportalapi-claim0
spec:
  storageClassName: osportalapi-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
