apiVersion: v1
kind: PersistentVolume
metadata:
  name: osscapi-pv-volume
  labels:
    type: local
spec:
  storageClassName: osscapi-pv-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osscapi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: osscapi-claim0
  name: osscapi-claim0
spec:
  storageClassName: osscapi-pv-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
