apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    io.kompose.service: osscapi
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 13082
      targetPort: 13082
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
