apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openslice
  creationTimestamp: null
  labels:
    io.openslice.service: portainer-claim0
  name: portainer-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
